[module]
  [module.hugoVersion]
    min = "0.41.0"

[params]
    remark42 = true
    remark42_host = "https://remark42.guelbandeira.com"
    remark42_site_id = "remark"
    plausible = true
    plausible_domain = "plausible.guelbandeira.com"
    plausible_script = "https://plausible.guelbandeira.com/js/pa-KAIFHbr9bPLR9_PJg4j5s.js"