[module]
  [module.hugoVersion]
    min = "0.41.0"

[params]
    plausible = true
    plausible_domain = "blog.guelbandeira.com"
    plausible_script = "https://plausible.guelbandeira.com/js/pa-KAIFHbr9bPLR9_PJg4j5s.js"