name = "Poison"
license = "GPL-3.0 License"
licenselink = "https://github.com/lukeorth/poison/blob/master/LICENSE.md"
description = "A pragmatic Hugo theme for bloggers.  Based on the classic \"Hyde\" design by mdo."
min_version = "0.101.0"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/lukeorth/poison"

# If you have a running demo of the theme.
demosite = "https://poison.lukeorth.com"

tags = ["blog", "personal", "dark", "dark-mode", "light", "minimal"]
features = ["blog", "katex", "table-of-contents", "tabs", "dark-mode", "series"]

[author]
    name = "Luke Orth"
    homepage = "https://lukeorth.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"

[params]
    remark42 = true
    remark42_host = "https://remark42.guelbandeira.com"
    remark42_site_id = "remark"

    plausible = true
    plausible_domain = "blog.guelbandeira.com"
    plausible_script = "https://plausible.guelbandeira.com/js/pa-KAIFHbr9bPLR9_PJg4j5s.js"